Repository cruiz24/HackTober_2020, pull requests merged in 2020-10, with the labels that each got.

#2 updated ':-' mark
  README.md
Labels: h2020, invalid

#4 Sd
  Hello_W/1
Labels: hacktober

#5 Ra
  Hello_W/1
Labels: good first issue, h2020, hacktober

#6 Update contributors.md
  contributors.md
Labels: good first issue, h2020, hacktober

#7 calculator. java
  Algorithms/calculator
Labels: good first issue, h2020, hacktober

#11 MultiplicationTable.java
  Algorithms/MultiplicationTable
Labels: good first issue, h2020, hacktober

#10 palindrome.java
  Algorithms/palindrome
Labels: enhancement, good first issue, h2020, hacktober

#12 prime number.java
  Algorithms/Prime number
Labels: good first issue, h2020, hacktober

#13 login page.java
  Algorithms/login page
Labels: enhancement, good first issue, h2020, hacktober

#14 .
  Algorithms/MultiplicationTable
  Algorithms/Prime number
  Algorithms/fibonacci series
  Algorithms/login page
  Algorithms/palindrome
Labels: documentation, h2020, hacktober
